title: 4log
theme: minima
show_drafts: true
list_title:

minima:
  skin: dark

plugins:
 - jekyll-titles-from-headings
 - jekyll-feed
 - jekyll-seo-tag
 
titles_from_headings:
  enabled: true
  strip_title: false
  collections: true
