import os
from pathlib import Path


PROJ_DIR = Path(__file__).parent.parent
BUILD_DIR = PROJ_DIR / 'src'
DOCS_DIR = PROJ_DIR / 'docs'
ARTICLES_DOCS_DIR = DOCS_DIR / 'articles'
TEMPLATES_DIR = BUILD_DIR / 'templates'
ARTICLE_TEMPLATE_FILE = TEMPLATES_DIR / 'article.jinja'
INDEX_TEMPLATE_FILE = TEMPLATES_DIR / 'index.jinja'
SITEMAP_TEMPLATE_FILE = TEMPLATES_DIR / 'sitemap.jinja'
RSS_TEMPLATE_FILE = TEMPLATES_DIR / 'rss.jinja'
INDEX_FILE = DOCS_DIR / 'index.html'
SITEMAP_FILE = DOCS_DIR / 'sitemap.xml'
RSS_FILE = DOCS_DIR / 'rss.xml'
AS_DIRS_IGNORE = ('drafts', )
ARTICLE_IMG_FILE = 'files/main-section.png'
SITE_NAME = 'ТехнологоблогЪ'
SITE_ADDRESS = 'https://www.kvdm.dev'

ANALYTICS_ENABLED_DEFAULT = False
ANALYTICS_SERVICE_ADDRESS = os.environ.get("ANALYTICS_SERVICE_ADDRESS", "")
ANALYTICS_SERVICE_TOKEN = os.environ.get("ANALYTICS_SERVICE_TOKEN", "")
ANALYTICS_SERVICE_JS = ANALYTICS_SERVICE_ADDRESS + "/umami.js"
ANALYTICS_SERVICE_PAGE = ANALYTICS_SERVICE_ADDRESS + os.environ.get("ANALYTICS_SERVICE_PAGE", "")

MONITORING_ENABLED_DEFAULT = False
MONITORING_SERVICE_ADDRESS = os.environ.get("MONITORING_SERVICE_ADDRESS", "")
MONITORING_SERVICE_PAGE = MONITORING_SERVICE_ADDRESS + os.environ.get("MONITORING_SERVICE_PAGE", "")

MEMOCARDS_ENABLED_DEFAULT = False
MEMOCARDS_SERVICE_ADDRESS = os.environ.get("MEMOCARDS_SERVICE_ADDRESS", "")

STATUSPAGE_ENABLED_DEFAULT = False
STATUSPAGE_SERVICE_ADDRESS = os.environ.get("STATUSPAGE_SERVICE_ADDRESS", "")

